version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: email_postgres
    environment:
      POSTGRES_DB: email_emulator
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: .
    container_name: email_backend
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/email_emulator
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ../frontend
    container_name: email_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pgdata: